### ISSUE TITLE
What was the architectural decision to use process flow in BRMS instead of BPM?

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/brms-coolstore-demo#34]
What was the architectural decision to use process flow in BRMS instead of BPM?

**Comment by alberttwong** [comment]
Another way to say it.... at what point to you use the process engine in BPM instead of BRMS?

**Comment by jmilliro** [comment]
The Ruleflow was used because I only needed to group together rules and order their execution.  If I needed to connect to an external service, such as REST or SOAP as part of my flow, then I would have used BPM.  In addition, all bpm processes are persisted, which can cause some overhead.  

Jason Milliron 

Senior Solutions Architect 
JBoss by Red Hat, Inc. 
630.865.4569 
jason.milliron@redhat.com 

http://jbossdemocentral.github.io 

----- Original Message -----

**Comment by eschabell** [comment]
Also this is a simple demo project to allow SA's to showcase the JBoss BRMS features.... not complex multi event streams or worries about development strategies down the road for rules. 

Easy to use, easy to setup, easy to repeat on all platforms is the goal here.

**Comment by alberttwong** [comment]
@jmilliro That makes sense.  Isn't it true that the process flow has the same capability in both products (BRMS, BPMS)?  I thought you can call external services in the process flow in BRMS.

**Comment by jmilliro** [comment]
Brms doesn't have rest/soap task available out of the box.

Thanks,

Jason Milliron
Senior Solutions Architect
JBoss by Red Hat, Inc.
jason.milliron@redhat.com


-----Original Message-----
